# Timeout in seconds that Limine will use before automatically booting.
timeout: 5
resolution=1920x1080
# The entry name that will be displayed in the boot menu.
/NTux OS
    # We use the Limine boot protocol.
    protocol: limine
    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    path: boot():/boot/kernel
    module_path: boot():/boot/modules/konsole.elf
    module_string: konsole
    module_path: boot():/boot/modules/login.elf
    module_string: login
    module_path: boot():/boot/modules/desktop.elf
    module_string: desktop
    module_path: boot():/boot/modules/installer.elf
    module_string: installer
    module_path: boot():/boot/modules/installer_term.elf
    module_string: installer_term
    module_path: boot():/boot/modules/deskconsole.elf
    module_string: deskconsole
    module_path: boot():/boot/modules/explorer.elf
    module_string: explorer
    module_path: boot():/boot/modules/editor.elf
    module_string: editor
    module_path: boot():/boot/modules/bench.elf
    module_string: bench
    module_path: boot():/boot/modules/imgview.elf
    module_string: imgview
    module_path: boot():/boot/modules/objview.elf
    module_string: objview
    module_path: boot():/boot/modules/flappy.elf
    module_string: flappy
    module_path: boot():/boot/modules/taskmgr.elf
    module_string: taskmgr
    module_path: boot():/boot/modules/tetris.elf
    module_string: tetris
    module_path: boot():/boot/modules/deskdemo.elf
    module_string: deskdemo
    module_path: boot():/boot/modules/screensaver.elf
    module_string: screensaver
    module_path: boot():/boot/modules/xeyes.elf 
    module_string: xeyes
    module_path: boot():/boot/modules/settings.elf
    module_string: settings
    module_path: boot():/boot/modules/partutil.elf
    module_string: partutil
    module_path: boot():/boot/modules/browser.elf
    module_string: browser
    module_path: boot():/boot/modules/paint.elf
    module_string: paint
    module_path: boot():/boot/modules/snake.elf
    module_string: snake
    module_path: boot():/boot/modules/snake2.elf
    module_string: snake2
    module_path: boot():/boot/modules/calc.elf
    module_string: calc
    module_path: boot():/boot/modules/test.elf
    module_string: test
    module_path: boot():/boot/modules/healthcheck.elf
    module_string: healthcheck
    module_path: boot():/boot/modules/lua.elf
    module_string: klua
# The entry name that will be displayed in the boot menu.
/NTux OS Recovery
    protocol: limine
    # We use the Limine boot protocol.
    path: boot():/boot/recovery/kernel
    module_path: boot():/boot/modules/konsole.elf
    module_string: konsole
    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    #module_path: boot():/boot/res/backgrounds/backgrounds.bmp
