/*
 * irq.c — IRQ handler registration and dispatch.
 *
 * The assembly IRQ stubs (in irq.asm) push the IRQ number onto the stack
 * and call irq_handler_c(). This function looks up the registered handler
 * for that IRQ and calls it. After the handler runs, it sends End-Of-
 * Interrupt (EOI) to both the APIC (if enabled) and the legacy PIC.
 */

#include <interrupt/irq.h>
#include <interrupt/pic.h>
#include <interrupt/apic/apic.h>
#include <drivers/framebuffer/kprint.h>

/* Stub table generated by irq.asm — each entry is a small trampoline */
extern uint64_t irq_stub_table[];

/* Registered handler functions, one per IRQ (index 0-15) */
void (*irq_handlers[16])(void) = {0};

void irq_register_handler(int irq, void (*handler)(void)) {
    if (irq < 16) {
        irq_handlers[irq] = handler;
    }
}

/*
 * C-level IRQ dispatch.
 * Called from the assembly stub with a pointer to saved register state.
 * The IRQ number is at stack[15] (see irq.asm for stack layout).
 */
void irq_handler_c(uint64_t *stack) {
    if (!stack) {
        return;
    }
    int irq = (int)stack[15];

    if (irq >= 0 && irq < 16 && irq_handlers[irq]) {
        irq_handlers[irq]();
    }

    /* Signal end-of-interrupt to the interrupt controllers */
    if (apic_uses_ioapic()) {
        apic_send_eoi();
    }
    pic_send_eoi(irq);
}
